# mobilepage-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobilepage
  template:
    metadata:
      labels:
        app: mobilepage
    spec:
      containers:
      - name: mobilepage
        image: 324761312512.dkr.ecr.us-east-1.amazonaws.com/mobilepage:latest
        ports:
        - containerPort: 80
        
---

# mobilepage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mobilepage
spec:
  selector:
    app: mobilepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80